### PR TITLE
Implementation of MicrosoftSupport  - using PSObject

### PR DESCRIPTION
**Pull request by vivesg**
Backend with PSObject 
Not an elegant solution but functional, i added this in a couple of hours of investigation.
It works but sure could be improved :)

### CODE REVIEW

**Comment by EvanBasalik** [comment]
Confused - why the need to do it with PowerShell? If we go the route of hard-coding the tenant IDs, we can just change the tenant ID when we make the call to set OOF.

**Comment by EvanBasalik** [comment]
ooooh - I think the why just occurred to me. When doing it with PowerShell, you are running it directly in the context of the user.

The best solution would be to get admin consent granted in the new tenant. We are working on that now.

**Comment by EvanBasalik** [comment]
I do like the idea of setting against multiple tenants simultaneously. On the roadmap....

**Comment by vivesg** [comment]
this was intended as a temp workaround only as the Microsoftsupport tenant the app is not registered in this way we don't need to have that permissions setup.
I added as a feature in File Enable Alternative backend method as a Beta feature

and uses modern Auth to connect to the exchange online PowerShell to set the OOF 
Regards,

**Pull request closed without merging**
